# Generated by Django 4.2.9 on 2025-10-22 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('unidad_medida', models.CharField(default='UND', max_length=20)),
                ('ultimo_costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artículo',
                'verbose_name_plural': 'Artículos',
                'db_table': 'articulo',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaPrecios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_operacion', models.CharField(choices=[('CREACION', 'Creación'), ('MODIFICACION', 'Modificación'), ('ELIMINACION', 'Eliminación'), ('CALCULO', 'Cálculo de Precio')], max_length=20)),
                ('tabla', models.CharField(max_length=50)),
                ('registro_id', models.IntegerField()),
                ('usuario', models.CharField(blank=True, max_length=100)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Precio',
                'verbose_name_plural': 'Auditorías de Precios',
                'db_table': 'auditoria_precios',
                'ordering': ['-fecha_operacion'],
            },
        ),
        migrations.CreateModel(
            name='CombinacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad_minima', models.IntegerField(default=1)),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto Fijo')], max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Combinación de Producto',
                'verbose_name_plural': 'Combinaciones de Productos',
                'db_table': 'combinacion_producto',
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('ruc', models.CharField(max_length=11, unique=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
                'db_table': 'empresa',
            },
        ),
        migrations.CreateModel(
            name='GrupoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Grupo de Artículo',
                'verbose_name_plural': 'Grupos de Artículos',
                'db_table': 'grupo_articulo',
            },
        ),
        migrations.CreateModel(
            name='LineaArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Línea de Artículo',
                'verbose_name_plural': 'Líneas de Artículos',
                'db_table': 'linea_articulo',
            },
        ),
        migrations.CreateModel(
            name='ListaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('GENERAL', 'General'), ('MAYORISTA', 'Mayorista'), ('MINORISTA', 'Minorista'), ('ESPECIAL', 'Especial')], max_length=20)),
                ('canal', models.CharField(blank=True, choices=[('TIENDA', 'Tienda Física'), ('ONLINE', 'Tienda Online'), ('DISTRIBUIDOR', 'Distribuidor'), ('CORPORATIVO', 'Corporativo')], max_length=20, null=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='precios.empresa')),
            ],
            options={
                'verbose_name': 'Lista de Precio',
                'verbose_name_plural': 'Listas de Precios',
                'db_table': 'lista_precio',
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=20)),
                ('direccion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sucursales', to='precios.empresa')),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'db_table': 'sucursal',
                'unique_together': {('empresa', 'codigo')},
            },
        ),
        migrations.CreateModel(
            name='ReglaPrecio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo_regla', models.CharField(choices=[('CANAL', 'Por Canal de Venta'), ('ESCALA_UNIDADES', 'Por Escala de Unidades'), ('ESCALA_MONTO', 'Por Escala de Monto'), ('MONTO_PEDIDO', 'Por Monto Total de Pedido'), ('COMBINACION', 'Por Combinación de Productos')], max_length=20)),
                ('prioridad', models.IntegerField(default=0)),
                ('canal', models.CharField(blank=True, choices=[('TIENDA', 'Tienda Física'), ('ONLINE', 'Tienda Online'), ('DISTRIBUIDOR', 'Distribuidor'), ('CORPORATIVO', 'Corporativo')], max_length=20, null=True)),
                ('cantidad_minima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cantidad_maxima', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_minimo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('monto_maximo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tipo_descuento', models.CharField(choices=[('PORCENTAJE', 'Porcentaje'), ('MONTO_FIJO', 'Monto Fijo')], max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('grupo_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='precios.grupoarticulo')),
                ('linea_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='precios.lineaarticulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reglas', to='precios.listaprecio')),
            ],
            options={
                'verbose_name': 'Regla de Precio',
                'verbose_name_plural': 'Reglas de Precio',
                'db_table': 'regla_precio',
                'ordering': ['-prioridad', 'fecha_creacion'],
            },
        ),
        migrations.AddField(
            model_name='listaprecio',
            name='sucursal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='listas_precios', to='precios.sucursal'),
        ),
        migrations.AddField(
            model_name='grupoarticulo',
            name='linea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='precios.lineaarticulo'),
        ),
        migrations.CreateModel(
            name='DetalleOrdenCompraCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reglas_aplicadas', models.JSONField(blank=True, default=list)),
                ('bajo_costo', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='precios.articulo')),
            ],
            options={
                'verbose_name': 'Detalle de Orden',
                'verbose_name_plural': 'Detalles de Órdenes',
                'db_table': 'detalle_orden_compra_cliente',
            },
        ),
        migrations.CreateModel(
            name='DetalleCombinacionProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_requerida', models.IntegerField(default=1)),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='precios.articulo')),
                ('combinacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='precios.combinacionproducto')),
                ('grupo_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='precios.grupoarticulo')),
                ('linea_articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='precios.lineaarticulo')),
            ],
            options={
                'verbose_name': 'Detalle de Combinación',
                'verbose_name_plural': 'Detalles de Combinaciones',
                'db_table': 'detalle_combinacion_producto',
            },
        ),
        migrations.AddField(
            model_name='combinacionproducto',
            name='lista_precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='combinaciones', to='precios.listaprecio'),
        ),
        migrations.AddField(
            model_name='articulo',
            name='grupo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articulos', to='precios.grupoarticulo'),
        ),
        migrations.CreateModel(
            name='PrecioArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bajo_costo', models.BooleanField(default=False)),
                ('autorizado_bajo_costo', models.BooleanField(default=False)),
                ('descuento_proveedor', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='precios.articulo')),
                ('lista_precio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios', to='precios.listaprecio')),
            ],
            options={
                'verbose_name': 'Precio de Artículo',
                'verbose_name_plural': 'Precios de Artículos',
                'db_table': 'precio_articulo',
                'unique_together': {('lista_precio', 'articulo')},
            },
        ),
    ]
